package main

func main() {
	println("\n**** Go Format Specifiers ****")

	println("\nDefault formats and type. Value: []int64{0, 1}")
	println("---------------------------------------------------")
	println("|Format           Verb        Description         |")
	println("---------------------------------------------------")
	println("[0 1]            %v          Default format")
	println("[]int64{0, 1}    %#v         Go-syntax format")
	println("[]int64          %T          The type of the value")
	println("---------------------------------------------------")

	println("\nInteger (indent, base, sign): Value: 15")
	println("-------------------------------------------------------------------------")
	println("|Format           Verb        Description                               |")
	println("-------------------------------------------------------------------------")
	println("15                %d          Base 10")
	println("+15               %+d         Always show sign")
	println("␣␣15               %4d         Pad with spaces (width 4, right justified)")
	println("15␣␣               -4d         Pad with spaces (width 4, left justified)")
	println("0015              %04d        Pad with zeroes (width 4)")
	println("1111              %b          Base 2")
	println("17                %o          Base 8")
	println("f                 %x          Base 16, lowercase")
	println("F                 %X          Base 16, uppercase")
	println("0xf               %#x         Base 16, with leading 0x")
	println("-------------------------------------------------------------------------")

	println("\nCharacter (quoted, Unicode). Value: 65   (Unicode letter A)")
	println("------------------------------------------------------")
	println("|Format           Verb        Description             |")
	println("------------------------------------------------------")
	println("A                 %c          Character")
	println("'A'               %q          Quoted character")
	println("U+0041            %U          Unicode")
	println("U+0041'A'         %#U         Unicode with character")
	println("------------------------------------------------------")

	println("\nBoolean (true/false): Use %t to format a boolean as true or false.")

	println("\nPointer (hex): Use %p to format a pointer in base 16 notation with leading 0x.")

	println("\nFloat (indent, precision, scientific notation): Value: 123.456")
	println("-----------------------------------------------------------------------")
	println("|Format           Verb        Description                             |")
	println("-----------------------------------------------------------------------")
	println("1.234560e+02      %e          Scientific notation")
	println("123.456000        %f          Decimal point, no exponent")
	println("123.46            %.2f        Default width, precision 2")
	println("␣␣123.46           %8.2f       Width 8, precision 2")
	println("123.456           %g          Exponent as needed, necessary digits only")
	println("-----------------------------------------------------------------------")

	println("\nString or byte slice (quote, indent, hex). Value: \"café\"")
	println("-------------------------------------------------------")
	println("|Format           Verb        Description             |")
	println("-------------------------------------------------------")
	println("café              %s          Plain string")
	println("␣␣café             %6s         Width 6, right justify")
	println("café␣␣             %-6s        Width 6, left justify")
	println("\"café\"            %q          Quoted string")
	println("636166c3a9        %x          Hex dump of byte values")
	println("63 61 66 c3 a9    % x         Hex dump with spaces")
	println("-------------------------------------------------------")

	println("\nSpecial values")
	println("----------------------------------------------")
	println("|Value           Description                  |")
	println("----------------------------------------------")
	println("\\a               U+0007 alert or bell")
	println("\\b               U+0008 backspace")
	println("\\\\               U+005c backslash")
	println("\\t               U+0009 horizontal tab")
	println("\\n               U+000A line feed or newline")
	println("\\f               U+000C form feed")
	println("\\r               U+000D carriage return")
	println("\\v               U+000b vertical tab")
	println("----------------------------------------------")

	println("Source: https://yourbasic.org/golang/fmt-printf-reference-cheat-sheet/")
}
